# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e98bb6096a92244a6a4989e649f2872592850944bce8e3df8f00f24df1af0dad209e0c6134ae4761065403cb5e32d205c6e8109ac04dedc7224fbc742527ab51

test:
  secret_key_base: 7c0343ac987266ad232b1832ffbf38045450eab4b33944caaae1ac9e9de45cd5d681718ef19c2d4936a255c2a26d1dcab9f7f799e32a590128501671be7bcce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
